server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: indexing-service
          uri: lb://indexing-service
          predicates:
            - Path=/index/**
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: crawler-group
      auto-offset-reset: earliest
